services:
  nginx:
    volumes:
      - ./nginx/conf/dev-frontend.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
      - static_volume:/django/staticfiles
      - media_volume:/django/media
    ports:
      - "80:8080"

  frontend:
    command: npm run dev
    build:
      context: ./frontend
    container_name: nextjs_app
    working_dir: /app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"